### ISSUE TITLE
Issue-VM Recovery

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/p2p-eth#112]
Automated Review Comments
Issues in block_manager.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (29, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (43, 'TODO found')

**Comment by PhantomFortune** [comment]
I got it.
