### ISSUE TITLE
Issue-updated testing"

### ISSUE THREAD

**Issue by johnsmith0212** [johnsmith0212/p2p-eth#140]
Automated Review Comments
Issues in parsing_test.go:
  - (6, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
Issues in testing.go:
  - (6, 'Hardcoded string found')
Issues in transaction.go:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')

**Comment by lind0118** [comment]
I got it.
